### ISSUE TITLE
uninitialized constant Sprockets::SassCacheStore

### ISSUE THREAD

**Issue by CodedBeardedSignedTaylor** [IcaliaLabs/sabisu-rails#26]
Hey there,

Currently, I can't render the index view for Sabisu because of the following error:

![screen shot 2015-05-13 at 1 10 29 pm](https://cloud.githubusercontent.com/assets/3003701/7617568/98c1f0d6-f971-11e4-8e9c-f60a2009a596.png)

Any idea what's going on here? Seems like maybe you called a depreciated class from Sprockets? I'm currently running with Rails 4.2.1.

**Comment by kurenn** [comment]
Try to update `compass-rails` gem to at least 2.0.2

```ruby
gem 'compass-rails', '~> 2.0.2'
```

**Comment by CodedBeardedSignedTaylor** [comment]
Cool. That took care of the Sass error. However, there's something else going on. 

![screen shot 2015-05-14 at 10 43 46 am](https://cloud.githubusercontent.com/assets/3003701/7635382/428df056-fa26-11e4-865c-0025c5c6e85f.png)

**Comment by kurenn** [comment]
How does your `sabisu_rails` initializer file looks like?...

**Comment by CodedBeardedSignedTaylor** [comment]
```
SabisuRails.setup do |config|

  # Base uri for posting the
  config.base_api_uri = 'api.marketplace.dev'

  # Ignored attributes for building the forms
  # config.ignored_attributes = %w{ created_at updated_at id }

  # HTTP methods
  # config.http_methods = %w{ GET POST PUT DELETE PATCH }

  # Headers to include on each request
  config.api_headers = { "Accept" => "application/vnd.marketplace.v1" }

  # Layout configuration
  # config.layout = "sabisu"

  # Resources on the api
  config.resources = [:users]

  # Application name
  # mattr_accessor :app_name
  # @@app_name = Rails.application.class.parent_name

  # Authentication
  # mattr_accessor :authentication_username
  # @@authentication_username = "admin"

  # mattr_accessor :authentication_password
  # @@authentication_password = "sekret"

end
```

**Comment by kurenn** [comment]
You need to have a default_resource set up, in this case the users, like:

```ruby
# Default resource
config.default_resource = :users
```

**Comment by CodedBeardedSignedTaylor** [comment]
I've tried that as well. Still no luck :(

**Comment by kurenn** [comment]
Did you restart the server?

**Comment by CodedBeardedSignedTaylor** [comment]
Yeah. The same issue still persists.

**Comment by kurenn** [comment]
This is the configuration for a sample project https://github.com/kurenn/market_place_api/blob/chapter8/config/initializers/sabisu_rails.rb

Let me know how it goes

**Comment by CodedBeardedSignedTaylor** [comment]
Yeah man, I've been using that same configuration. Same errors persist.

**Comment by kurenn** [comment]
Do you have the repo online?

**Comment by CodedBeardedSignedTaylor** [comment]
Yep! 

[https://github.com/CodedBeardedSignedTaylor/RailsApiDemo](https://github.com/CodedBeardedSignedTaylor/RailsApiDemo)

**Comment by kurenn** [comment]
I manage to make it work:

You just need to fetch the `sabisu` gem from the github repo:

```ruby
gem 'sabisu_rails', github: "IcaliaLabs/sabisu-rails"
```

Run the bundle command to install it and restart the pow server:

```console
% bundle install; touch tmp/restart.txt
```

If you visit the explorer now, it should work!

**Comment by CodedBeardedSignedTaylor** [comment]
Excellent!

**Comment by CodedBeardedSignedTaylor** [comment]
For documentation purposes, is there a need to specify those gem versions for users of Rails 4.2+?

Let me know if there is. I'd be happy to go in there and insert it.

**Comment by kurenn** [comment]
We can probably publish a wiki page, or on the project [README](https://github.com/IcaliaLabs/sabisu-rails/blob/master/README.md)

I would say on the readme, can you place the PR?

**Comment by CodedBeardedSignedTaylor** [comment]
Sure thing. I'll probably end up getting to it tomorrow evening.

**Comment by kurenn** [comment]
Solved with https://github.com/IcaliaLabs/sabisu-rails/pull/27
