### ISSUE TITLE
undefined method `columns' - Chapter 3 

### ISSUE THREAD

**Issue by tknazn** [IcaliaLabs/sabisu-rails#29]
I try to follow the marketapp api tutorial and struggle to set up the sabisu-rails app. 
I'm using Rails 4.2, ruby 2.2. and mongoid

![screen shot 2015-05-22 at 11 32 21 am](https://cloud.githubusercontent.com/assets/751046/7775154/32fac208-0076-11e5-8c32-d6f4eeab38d2.png)

Below are my setting
![screen shot 2015-05-22 at 11 35 05 am](https://cloud.githubusercontent.com/assets/751046/7775179/673fb870-0076-11e5-9625-5910579f385c.png)

![screen shot 2015-05-22 at 11 36 43 am](https://cloud.githubusercontent.com/assets/751046/7775212/a669ec00-0076-11e5-9bd2-ec15ed112d1e.png)

Thanks in advance for helping!

**Comment by kurenn** [comment]
Sabisu does not support mongo, the `columns` method has to be with `ActiveRecord::Base` parent class

**Comment by tknazn** [comment]
Thakn you
