### ISSUE TITLE
NoMethodError throwing from ExplorerController#index

### ISSUE THREAD

**Issue by RailsCod3rFuture** [IcaliaLabs/sabisu-rails#31]
My stacktrace says undefined method `singularize' for nil:NilClass when I access the controller for Sabisu. Maybe, you have a work around or quick fix? I'm using Windows btw.

**Comment by kurenn** [comment]
You probably have to set up a default resource on the initializer:

```ruby
SabisuRails.setup do |config|

  config.base_api_uri = ENV['API_URL']
  config.resources = [:products,:users]
  config.default_resource = "users"

end
```
