### ISSUE TITLE
ArgumentError in SabisuRails::Explorer#index

### ISSUE THREAD

**Issue by maichomper** [IcaliaLabs/sabisu-rails#33]
I'm getting the following error after following the Sabisu installation in Chapter 3

![screen shot 2015-08-21 at 3 32 31 pm](https://cloud.githubusercontent.com/assets/5483173/9418466/e49c02de-4819-11e5-822f-02f22019e378.png)

Here's the full stack trace: 

Started GET "/sabisu_rails/explorer" for ::1 at 2015-08-21 15:29:56 -0500
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by SabisuRails::ExplorerController#index as HTML
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/bundler/gems/sabisu-rails-af7499e87912/app/views/sabisu_rails/explorer/index.html.erb within layouts/sabisu_rails (111.6ms)
Warning. Error encountered while reading cache 8f78c4ec0ae0a06182e311b21228381a3989592f/application.css.scssc: wrong number of arguments (2 for 1)

Completed 500 Internal Server Error in 379ms

ActionView::Template::Error (wrong number of arguments (3 for 2)):
    10:   <title>Sabisu Explorer</title>
    11:
    12:   
    13:   <%= stylesheet_link_tag "sabisu_rails/application", :cache => true %>
    14:   <%= csrf_meta_tag %>
    15:
    16:   
  sprockets (3.3.2) lib/sprockets/cache/file_store.rb:81:in `set'
  sprockets (3.3.2) lib/sprockets/sass_cache_store.rb:14:in `_store'
  sass (3.4.16) lib/sass/cache_stores/base.rb:51:in `store'
  sass (3.4.16) lib/sass/engine.rb:414:in `_to_tree'
  sass (3.4.16) lib/sass/engine.rb:309:in `to_tree'
  sass (3.4.16) lib/sass/engine.rb:343:in `_dependencies'
  sass (3.4.16) lib/sass/engine.rb:331:in `dependencies'
  compass-rails (2.0.2) lib/compass-rails/patches/sass_importer.rb:36:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (3.3.2) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.3.2) lib/sprockets/loader.rb:126:in `load_from_unloaded'
  sprockets (3.3.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.3.2) lib/sprockets/loader.rb:286:in `fetch_asset_from_dependency_cache'
  sprockets (3.3.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.3.2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.3.2) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.3.2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:75:in `call_processor'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:56:in `reverse_each'
  sprockets (3.3.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.3.2) lib/sprockets/loader.rb:126:in `load_from_unloaded'
  sprockets (3.3.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.3.2) lib/sprockets/loader.rb:286:in `fetch_asset_from_dependency_cache'
  sprockets (3.3.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.3.2) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.3.2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.3.2) lib/sprockets/environment.rb:30:in `find_asset'
  sprockets (3.3.2) lib/sprockets/base.rb:92:in `[]'
  sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `map'
  sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/bundler/gems/sabisu-rails-af7499e87912/app/views/layouts/sabisu_rails.html.erb:13:in `___sers_micho__rvm_rubies_ruby_______lib_ruby_gems_______bundler_gems_sabisu_rails_af____e______app_views_layouts_sabisu_rails_html_erb__4335166339722178572_2223937020'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:143:in `render'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.2.0) lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/bundler/gems/sabisu-rails-af7499e87912/app/controllers/sabisu_rails/explorer_controller.rb:8:in `index'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
  /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (10.5ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.1ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (9.7ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (35.9ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.5ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.4ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.2ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (14.5ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (0.2ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.4ms)
  Rendered /Users/micho/.rvm/rubies/ruby-2.1.1/lib/ruby/gems/2.1.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (33.0ms)

**Comment by kurenn** [comment]
Can I see the Sabisu Initializer file?

**Comment by tuanlv1206** [comment]
I got this error, Can anyone help me?
