### ISSUE TITLE
undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by plays2** [IcaliaLabs/sabisu-rails#41]
Following this: http://apionrails.icalialabs.com/book/chapter_three

After login I get this:

>    NoMethodError in SabisuRails::ExplorerController#index
>    undefined method `+' for nil:NilClass

```
 Extracted source (around line #1532):         
        address() + (port == HTTP.https_default_port ? '' : ":#{port()}")
      else
        address() + (port == HTTP.http_default_port ? '' : ":#{port()}")
      end
    end
```

I added the 'config.base_api_uri = "api.marketplaceapi.dev" to the config file. Not sure where to even begin/:

**Comment by kurenn** [comment]
I think this is related to devise new IPaddress attribute for users...

**Comment by plays2** [comment]
I forgot I posted this. It was a silly mistake on my end. My b
