### ISSUE TITLE
NoMethodError in SabisuRails::Explorer#index

### ISSUE THREAD

**Issue by rohitgoyal** [IcaliaLabs/sabisu-rails#43]
Rbenv version 2.1.2
rails: 4.0.2

NoMethodError in SabisuRails::Explorer#index

Showing /Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/views/sabisu_rails/explorer/index.html.erb where line #36 raised:
undefined method `to_datetime' for 0:Fixnum

Extracted source (around line #36):
             <div class="appeareable">
               <% @explorer.resource_columns.each do |column| %>
                 <%= f.input column, input_html: {name: "#{@explorer.resource_name}[#{column}]" }, as: @explorer.column_type(column), required: @explorer.required_attribute?(column) %>
             <% end %>
             </div>

Full stack:

activesupport (4.0.2) lib/active_support/core_ext/date_time/calculations.rb:161:in `<=>'
activesupport (4.0.2) lib/active_support/core_ext/time/calculations.rb:286:in`compare_with_coercion'
activesupport (4.0.2) lib/active_support/time_with_zone.rb:214:in `<=>'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:793:in`=='
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:793:in `select_year'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:1025:in`block in build_selects_from_types'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:1023:in `each'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:1023:in`build_selects_from_types'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:704:in `select_datetime'
actionpack (4.0.2) lib/action_view/helpers/tags/date_select.rb:14:in`render'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:327:in `datetime_select'
actionpack (4.0.2) lib/action_view/helpers/date_helper.rb:1079:in`datetime_select'
simple_form (3.2.1) lib/simple_form/inputs/date_time_input.rb:10:in `input'
simple_form (3.2.1) lib/simple_form/components/label_input.rb:28:in`call'
simple_form (3.2.1) lib/simple_form/components/label_input.rb:28:in `deprecated_component'
simple_form (3.2.1) lib/simple_form/components/label_input.rb:14:in`label_input'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in `call'
simple_form (3.2.1) lib/simple_form/wrappers/leaf.rb:19:in`render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:28:in `block in render'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in`each'
simple_form (3.2.1) lib/simple_form/wrappers/many.rb:26:in `render'
simple_form (3.2.1) lib/simple_form/wrappers/root.rb:15:in`render'
simple_form (3.2.1) lib/simple_form/form_builder.rb:116:in `input'
/Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/views/sabisu_rails/explorer/index.html.erb:36:in`block (2 levels) in ___sers_rohitgoyal__rvm_gems_ruby_______bundler_gems_sabisu_rails_e____fe_ba___app_views_sabisu_rails_explorer_index_html_erb___144971340280483342_70174084236280'
/Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/views/sabisu_rails/explorer/index.html.erb:35:in `each'
/Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/views/sabisu_rails/explorer/index.html.erb:35:in`block in ___sers_rohitgoyal__rvm_gems_ruby_______bundler_gems_sabisu_rails_e____fe_ba___app_views_sabisu_rails_explorer_index_html_erb___144971340280483342_70174084236280'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:200:in`with_output_buffer'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionpack (4.0.2) lib/action_view/helpers/form_helper.rb:435:in`form_for'
furatto (1.4.0) lib/furatto_rails_helpers/action_view_form_builder_extension.rb:8:in `form_for_with_furatto'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:26:in`block in simple_form_for'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
simple_form (3.2.1) lib/simple_form/action_view_extensions/form_helper.rb:25:in`simple_form_for'
/Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/views/sabisu_rails/explorer/index.html.erb:13:in `___sers_rohitgoyal__rvm_gems_ruby_______bundler_gems_sabisu_rails_e____fe_ba___app_views_sabisu_rails_explorer_index_html_erb___144971340280483342_70174084236280'
actionpack (4.0.2) lib/action_view/template.rb:143:in`block in render'
activesupport (4.0.2) lib/active_support/notifications.rb:161:in `instrument'
actionpack (4.0.2) lib/action_view/template.rb:141:in`render'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:49:in `block (2 levels) in render_template'
actionpack (4.0.2) lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.2) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:48:in `block in render_template'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:56:in`render_with_layout'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:47:in `render_template'
actionpack (4.0.2) lib/action_view/renderer/template_renderer.rb:17:in`render'
actionpack (4.0.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionpack (4.0.2) lib/action_view/renderer/renderer.rb:23:in`render'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:127:in `_render_template'
actionpack (4.0.2) lib/action_controller/metal/streaming.rb:219:in`_render_template'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:120:in `render_to_body'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:33:in`render_to_body'
actionpack (4.0.2) lib/action_controller/metal/renderers.rb:26:in `render_to_body'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:97:in`render'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in`block (2 levels) in render'
activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/rohitgoyal/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in`realtime'
activesupport (4.0.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:41:in`block in render'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.0.2) lib/action_controller/metal/mime_responds.rb:191:in`respond_to'
/Users/rohitgoyal/.rvm/gems/ruby-2.3.0/bundler/gems/sabisu-rails-e5443fe6ba38/app/controllers/sabisu_rails/explorer_controller.rb:8:in `index'
actionpack (4.0.2) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (4.0.2) lib/active_support/callbacks.rb:383:in`_run__779288375914536988__process_action__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in`block in process_action'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in`process_action'
actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
actionpack (4.0.2) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in`process'
actionpack (4.0.2) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
actionpack (4.0.2) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in`dispatch'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in`block in call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
railties (4.0.2) lib/rails/engine.rb:511:in`call'
railties (4.0.2) lib/rails/railtie/configurable.rb:30:in `method_missing'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in`block in call'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in`call'
actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
warden (1.2.6) lib/warden/manager.rb:35:in`block in call'
warden (1.2.6) lib/warden/manager.rb:34:in `catch'
warden (1.2.6) lib/warden/manager.rb:34:in`call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:25:in`call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in`context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in`call'
activerecord (4.0.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in`call'
activerecord (4.0.2) lib/active_record/migration.rb:369:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in`block in call'
activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__2777843919165879251__call__callbacks'
activesupport (4.0.2) lib/active_support/callbacks.rb:80:in`run_callbacks'
actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.2) lib/rails/rack/logger.rb:38:in`call_app'
railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in`block in tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in`tagged'
railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in`call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in`call'
activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in`call'
actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in`call'
railties (4.0.2) lib/rails/engine.rb:511:in `call'
railties (4.0.2) lib/rails/application.rb:97:in`call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in`call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
/Users/rohitgoyal/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in`service'
/Users/rohitgoyal/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/Users/rohitgoyal/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in`block in start_thread'

**Comment by kurenn** [comment]
Check out issue #9 and #35
