### ISSUE TITLE
difference with postman?

### ISSUE THREAD

**Issue by BKSpurgeon** [IcaliaLabs/sabisu-rails#47]
Hi all

i'm trying to understand why sabisu is different to postman? any advice would be most appreciated.

rgds

Ben

**Comment by kurenn** [comment]
I would say that is something that you don't install or depends on Chrome, which some people won't use,  there is not huge difference, I just wanted to reduce the layers on the development flow and make an easier way to inspect api's

**Comment by BKSpurgeon** [comment]
ok thank you, appreciate it.
